[package]
name = "stagcrest-mod-sdk"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
stagcrest-protocol.workspace = true
serde.workspace = true
serde_json.workspace = true
wit-bindgen = { workspace = true, optional = true }

[features]
default = []
guest = ["wit-bindgen"]
