[package]
name = "stagcrest-content"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
stagcrest-modrinth.workspace = true
stagcrest-storage.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
thiserror.workspace = true
tracing.workspace = true
reqwest.workspace = true
zip.workspace = true

[dev-dependencies]
tempfile = "3"
