[package]
name = "stagcrest-modrinth"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
reqwest.workspace = true
sha1.workspace = true
percent-encoding.workspace = true

[dev-dependencies]
serde_json.workspace = true
