[package]
name = "stagcrest-net"
version.workspace = true
edition.workspace = true

[dependencies]
stagcrest-protocol.workspace = true
serde.workspace = true
postcard.workspace = true
glam.workspace = true
thiserror.workspace = true
tokio.workspace = true
socket2.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
