#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# Keep in sync with DEFAULT_MC_BLOCK_TEXTURES in
# crates/stagcrest-mod-host/src/resourcepack.rs
BLOCK_TEXTURES=(
  stone
  dirt
  grass_block_top
  grass_block_side
  grass_block_side_overlay
  cobblestone
  oak_planks
  glass
  bedrock
  redstone_dust_dot
  redstone_dust_line0
  redstone_torch_off
  redstone_torch
  redstone_block
  lever
  repeater
)

COLORMAPS=(grass foliage)

usage() {
  cat <<'EOF'
Usage: prepare-web-resourcepack.sh <source-pack-dir> [output-pack-dir]

Create a minimal Minecraft-format resource pack for web deploys.

Arguments:
  source-pack-dir   Full pack folder (must contain pack.mcmeta)
  output-pack-dir   Destination under resourcepacks/ (default: web)

Writes resourcepacks/resourcepacks.toml pointing at the output folder.
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

if [[ $# -lt 1 ]]; then
  usage >&2
  exit 1
fi

SOURCE_PACK="$(cd "$1" && pwd)"
OUTPUT_NAME="${2:-web}"
OUTPUT_PACK="$ROOT/resourcepacks/$OUTPUT_NAME"
MANIFEST_PATH="$ROOT/resourcepacks/resourcepacks.toml"

if [[ ! -f "$SOURCE_PACK/pack.mcmeta" ]]; then
  echo "error: missing pack.mcmeta in $SOURCE_PACK" >&2
  exit 1
fi

rm -rf "$OUTPUT_PACK"
mkdir -p "$OUTPUT_PACK/assets/minecraft/textures/block"
mkdir -p "$OUTPUT_PACK/assets/minecraft/textures/colormap"

cp "$SOURCE_PACK/pack.mcmeta" "$OUTPUT_PACK/"
if [[ -f "$SOURCE_PACK/LICENSE.txt" ]]; then
  cp "$SOURCE_PACK/LICENSE.txt" "$OUTPUT_PACK/"
fi

missing=0
for name in "${BLOCK_TEXTURES[@]}"; do
  src="$SOURCE_PACK/assets/minecraft/textures/block/${name}.png"
  dst="$OUTPUT_PACK/assets/minecraft/textures/block/${name}.png"
  if [[ ! -f "$src" ]]; then
    echo "warning: missing block texture $src" >&2
    missing=$((missing + 1))
    continue
  fi
  cp "$src" "$dst"
done

for name in "${COLORMAPS[@]}"; do
  src="$SOURCE_PACK/assets/minecraft/textures/colormap/${name}.png"
  dst="$OUTPUT_PACK/assets/minecraft/textures/colormap/${name}.png"
  if [[ -f "$src" ]]; then
    cp "$src" "$dst"
  else
    echo "note: colormap $name.png not in source pack; bundled fallback will be used"
  fi
done

cat >"$MANIFEST_PATH" <<EOF
# Generated by scripts/prepare-web-resourcepack.sh — slim pack for web deploys.

[[packs]]
id = "web"
path = "$OUTPUT_NAME"
enabled = true
EOF

copied_blocks=$(find "$OUTPUT_PACK/assets/minecraft/textures/block" -name '*.png' | wc -l)
echo "Prepared web resource pack at resourcepacks/$OUTPUT_NAME ($copied_blocks block textures)"
echo "Wrote $MANIFEST_PATH"

if [[ "$missing" -gt 0 ]]; then
  echo "warning: $missing required block texture(s) were missing from the source pack" >&2
  exit 1
fi
